import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-0 w-full py-2 backdrop-blur-sm">
          <p className="text-center">Harshana Abeyaratne (
            <a href="https://www.linkedin.com/in/harshanaa/" className="text-blue-700 underline decoration-dashed">Linkedin</a>,
            <a href="https://github.com/harshq" className="text-blue-700 underline decoration-dashed">Github</a>)</p>
        </div>
      </body>
    </html>
  );
}
